# Lab 03.02: Introduction to PyTorch  

In [1]:
import torch

### PyTorch Tensors

### Construct a vector of 3 elements

In [2]:
x=torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


### Construct a  2 x 2 matrix

In [3]:
A=torch.Tensor( [ [5.3,2.1] , [0.2,2.1] ] )
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


### Construct a random 10 x 2 matrix

In [4]:
A=torch.rand(10,2)
print(A)

tensor([[0.7498, 0.2691],
        [0.8693, 0.1975],
        [0.0021, 0.2302],
        [0.6206, 0.1565],
        [0.1913, 0.2585],
        [0.8053, 0.2235],
        [0.3175, 0.8906],
        [0.6373, 0.0266],
        [0.3859, 0.1007],
        [0.1555, 0.8744]])


### Construct a 10 x 2 matrix filled with zeros

In [5]:
A=torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Construct a 5 x 2 x 2 random Tensor 

In [6]:
B = torch.rand(5,2,2)
print(B)

tensor([[[0.0177, 0.9504],
         [0.9582, 0.0946]],

        [[0.1436, 0.8798],
         [0.5370, 0.3571]],

        [[0.6100, 0.8139],
         [0.1748, 0.0567]],

        [[0.0237, 0.6934],
         [0.1311, 0.3432]],

        [[0.8923, 0.2385],
         [0.7977, 0.8092]]])


In [7]:
B.size()

torch.Size([5, 2, 2])

In [8]:
B.dim()

3

### Size and Dimension of a Tensor 

#### A 3-dimensional Tensor 

In [9]:
A=torch.rand(3,2,2)
print(A)

tensor([[[0.8826, 0.2284],
         [0.7530, 0.2435]],

        [[0.2213, 0.6198],
         [0.8820, 0.9255]],

        [[0.5898, 0.3268],
         [0.3918, 0.9752]]])


In [10]:
print(  A.dim()   )

3


In [11]:
print(  A.size()   )

torch.Size([3, 2, 2])


In [12]:
print(  A.size(0)  )

3


#### A 2-dimensional Tensor 

In [13]:
B=torch.rand(3,5)
print(B)

tensor([[0.7671, 0.6470, 0.7702, 0.6315, 0.4696],
        [0.7422, 0.5464, 0.1165, 0.6252, 0.5320],
        [0.9052, 0.0902, 0.5475, 0.0883, 0.6006]])


In [14]:
print( B.dim()  )

2


In [15]:
print( B.size()  )

torch.Size([3, 5])


In [16]:
print( B.size(0) )

3


In [17]:
print( B.size(1) )

5


#### A 1-dimensional Tensor

In [18]:
x=torch.rand(7)
print(x)

tensor([0.8747, 0.9436, 0.9673, 0.3596, 0.0489, 0.9237, 0.5866])


In [19]:
print( x.dim() )

1


In [20]:
print( x.size() )

torch.Size([7])


### Adding and multiplying tensors

In [21]:
A=torch.rand(2,2)
B=torch.rand(2,2)

C=2*B
D=A+C
E=A*B

print(A)
print('')
print(B)
print('')
print(C)
print('')
print(C)
print('')
print(E)

tensor([[0.7513, 0.6579],
        [0.6255, 0.2182]])

tensor([[0.4870, 0.2859],
        [0.7319, 0.6777]])

tensor([[0.9740, 0.5718],
        [1.4638, 1.3553]])

tensor([[0.9740, 0.5718],
        [1.4638, 1.3553]])

tensor([[0.3659, 0.1881],
        [0.4578, 0.1479]])


### Floats versus integers

In [22]:
x=torch.Tensor([1.2 , 2.5])
print(x)
print(x.type())

tensor([1.2000, 2.5000])
torch.FloatTensor


In [23]:
y=torch.LongTensor([5,6])
print(y)
print(y.type())

tensor([5, 6])
torch.LongTensor


In [24]:
y=y.float()
print(y)
print(y.type())

tensor([5., 6.])
torch.FloatTensor


In [25]:
x=x.long()
print(x)
print(x.type())

tensor([1, 2])
torch.LongTensor


### Other functions

In [26]:
x=torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [27]:
x=torch.randperm(10)
print(x)
print(x.type())

tensor([1, 3, 5, 8, 4, 6, 0, 2, 7, 9])
torch.LongTensor


In [28]:
x=torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


### Tips

Check tensor sizes for algebra computations like multiplication torch.mm(X1,X2) with X1.size(), X2.size()

Check tensor type for data manipulations with X.type()

### Reshaping a tensor

In [29]:
x=torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [30]:
print( x.view(2,5) )

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [31]:
print( x.view(5,2) )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Note that the original tensor x was NOT modified

In [32]:
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


### To make the change permanent you need to create a new tensor

In [33]:
y=x.view(5,2)

print(x)
print('')
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


### Slicing a tensor

In [34]:
print( y )

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [35]:
print( y[0] )

tensor([0, 1])


In [36]:
print( y[1] )

tensor([2, 3])


In [37]:
v = y[2]
print(v)

tensor([4, 5])


### Extract row 1 (included) to row 4 (excluded)

In [38]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [39]:
print( y[1:4] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


In [40]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2, 3],
        [4, 5],
        [6, 7]])


### Let check the sizes after slicing

In [41]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [42]:
z= y[1:1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2, 3],
        [4, 5],
        [6, 7]])

dimension= 2
torch.Size([3, 2])


In [43]:
v=y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2, 3])

dimension= 1
torch.Size([2])


### Acessing the entries of a Tensor

In [44]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [45]:
print(y)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [46]:
a=y[4,0]
print(a) # a is a scalar, not a tensor

tensor(8)


In [47]:
print(a.dim())
print(a.size())

0
torch.Size([])


### A matrix is 2-dimensional Tensor
### A row of a matrix is a 1-dimensional Tensor
### An entry of a matrix is a 0-dimensional  Tensor

### 0-dimensional Tensor are scalar!

### If we want to convert a 0-dimensional Tensor into  python number, we need to use item()

In [48]:
b=a.item()
print(a)
print(type(a))
print(b)
print(type(b))

tensor(8)
<class 'torch.Tensor'>
8
<class 'int'>
